In [34]:
import numpy as np

In [35]:
L = [1,2,3] # Python List

In [36]:
A = np.array([1,2,3]) # NumPy Array

In [37]:
for e in L: # 'e' for 'element'
    print(e)

1
2
3


In [38]:
for e in A:
    print(e)

1
2
3


In [39]:
L.append(4) # Append item to list

In [40]:
L

[1, 2, 3, 4]

In [41]:
# Cannot do "A.append(4). This is because unlike a list, the size of an array is fixed."
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
L + [5]

[1, 2, 3, 4, 5]

In [ ]:
A + np.array([4]) 
# Element 4 is added to every element in A. This is called broadcasting in NumPy nomenclature.
# Technically in math this is illegal, you can't add two vectors of different sizes, but in NumPy this makes sense.
# NumPy is about doing math, which is why the plus operator does an actual mathematical operation
# https://numpy.org/doc/stable/user/basics.broadcasting.html

array([5, 6, 7])

In [ ]:
A + np.array([4,5,6])
# Plus sign is intelligent. It broadcasts when you add a scalar to an array, and adding an array to an array does regular vector addition. 

array([5, 7, 9])

In [ ]:
A + np.array([4,5]) # Error, can't add vectors of different sizes.

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
2 * A # Scalar and multiplication: broadcasting.

array([2, 4, 6])

In [ ]:
2 * L # This just does repetition, which means you can't multiply a list by a non-int number

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L2 = []
for e in L:
    L2.append(e + 3)

In [ ]:
L2

[4, 5, 6, 7]

In [ ]:
# Same as cell 17, but with list comprehension. List comprehension is the most common comprehension
# https://towardsdatascience.com/4-types-of-comprehensions-in-python-2fbeafdf2fda
# my_list = [<expression> for <item> in <iterable> if <condition>]
# condition optional
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [ ]:
L**2 # Error: doesn't work with list, but the below command works

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
L2 = [e**2 for e in L]
L2

[1, 4, 9, 16]

In [ ]:
A**2 # On the contrary, it works with NumPy arrays. 
# In general, applying a function to an array very often applies it element wise. 

array([1, 4, 9])

In [42]:
np.sqrt(A) # Other functions on arrays

array([1.        , 1.41421356, 1.73205081])

In [43]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [44]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [45]:
np.tanh(A) # Hyperbolic tangent, common in deep learning

array([0.76159416, 0.96402758, 0.99505475])