In [3]:
# Typing data by hand is not feasible when data has hundreds of dimensions
# Synthetic data can be used to test efficacy of our models.

# Array of all zeros
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.random()

0.02288612236556209

In [10]:
np.random.random((2,3))

array([[0.1193711 , 0.88481118, 0.82908149],
       [0.37034521, 0.1636773 , 0.75210418]])

In [12]:
np.random.randn(2,3)

array([[-1.81939758,  1.42611423,  1.08501614],
       [-0.02595722,  2.21864627, -0.63946396]])

In [15]:
R = np.random.randn(10000)

In [16]:
R.mean()  # Instance Method

0.005610392321705379

In [17]:
np.mean(R)   # Top-level function

0.005610392321705379

In [18]:
R.var()

1.0092961059268886

In [19]:
R.std()

1.0046373006846245

In [20]:
R = np.random.randn(10000,3)

In [21]:
R.mean(axis=0)  # Mean of each column

array([-0.00819753, -0.00041474, -0.00664035])

In [23]:
R.mean(axis=1).shape

(10000,)

In [25]:
np.cov(R).shape

# cov treats every 

(10000, 10000)

In [26]:
np.cov(R.T)

array([[1.00011059, 0.00948995, 0.01087786],
       [0.00948995, 0.99135824, 0.02069535],
       [0.01087786, 0.02069535, 0.98413491]])

In [27]:
np.cov(R, rowvar = False)  # Same as above

array([[1.00011059, 0.00948995, 0.01087786],
       [0.00948995, 0.99135824, 0.02069535],
       [0.01087786, 0.02069535, 0.98413491]])

In [31]:
np.random.randint(0,10, size = (3,3))

array([[6, 6, 2],
       [4, 1, 5],
       [4, 6, 6]])

In [32]:
np.random.choice(10,size=(3,3))

array([[3, 5, 6],
       [0, 7, 2],
       [2, 0, 2]])