In [2]:
# Can think of 2D arrays as matrices
# numpy array can have any number of dimensions, but matrices are always 2D
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [3]:
L[0]  # Returns first row of L

[1, 2]

In [4]:
L[0][1]

2

In [5]:
import numpy as np
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [6]:
A[0][1]

2

In [7]:
A[0,1]

2

In [8]:
A[:,0]  # Returns colummn at index 0
# Colon means select everything in this dimension

array([1, 3])

In [9]:
A.T  # Transpose

array([[1, 3],
       [2, 4]])

In [10]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [11]:
np.exp(L)  # Returns a np array, even with list input

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [12]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
A.dot(B)  # Matrix multiplication, which is a generalization of dot product


array([[ 9, 12, 15],
       [19, 26, 33]])

In [14]:
A.dot(B.T)
# Inner dimensions must match for matrix multiplication

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
np.linalg.det(A)

-2.0000000000000004

In [ ]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

In [ ]:
np.trace(A)

5

In [ ]:
np.diag(A)

array([1, 4])

In [ ]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [ ]:
np.linalg.eig(A)  # Eigen decomposition, returns array with eigenvalues, and array with eigenectors

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [15]:
Lam, V = np.linalg.eig(A)

In [16]:
V[:,0] * Lam[0] == A @ V[:,0]
# Should return True and True

array([ True, False])

In [18]:
V[:,0] * Lam[0], A @ V[:,0]


(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [19]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])
# Returns True if two arrays are element-wise equal within a tolerance.


True

In [20]:
np.allclose(V @ np.diag(Lam), A @ V)

True